# This file contains all constants and default configuration values for the application.

from PyQt5.QtGui import QColor, QFont
from PyQt5.QtCore import Qt

# --- ROS2 CONFIGURATION ---
C_AMR_ID = 16
TOTAL_ROBOT_COUNT = 30

# --- GENERAL SETTINGS ---
WINDOW_TITLE = f"C-AMR Agent Digital Twin - ID: {C_AMR_ID}"
UPDATE_INTERVAL_MS = 16
PIXELS_PER_METER = 20

# --- UI CONFIGURATION ---
CONFIG_PANEL_WIDTH = 220
INFO_PANEL_WIDTH = 280
GRID_CELL_SIZE = 20
NODE_DIAMETER = 4
ARROW_SIZE = 10
STATION_SIZE = 4

# --- UI STROKE WIDTHS ---
GRID_PEN_WIDTH = 0.25
OBSTACLE_PEN_WIDTH = 0.5
TRAFFIC_PEN_WIDTH = 0.5
DIVIDER_PEN_WIDTH = 0.5 # Dashed line for lane separation

# --- OBSTACLE & WAYPOINT CONFIGURATION ---
WALKABLE_MARGIN_METERS = 1.0
WALKABLE_MARGIN_PIXELS = WALKABLE_MARGIN_METERS * PIXELS_PER_METER
NODE_SPACING_M = 2.0
NODE_SPACING_PX = NODE_SPACING_M * PIXELS_PER_METER
NODE_CONNECTION_MAX_DIST_M = 15.0
NODE_CONNECTION_MAX_DIST_PX = NODE_CONNECTION_MAX_DIST_M * PIXELS_PER_METER
MIN_OBSTACLE_WIDTH_PX = 3.0 * PIXELS_PER_METER

# --- DEFAULT MAP CONFIGURATION ---
DEFAULT_MAP_WIDTH_M = 50.0
DEFAULT_MAP_HEIGHT_M = 50.0
DEFAULT_ROW_COUNT = 6
DEFAULT_NODE_COUNT = 100
DEFAULT_OBSTACLE_HEIGHT_M = 5.0
DEFAULT_OBSTACLE_SPACING_M = 3.0

# --- ROBOT CONFIGURATION ---
DEFAULT_ROBOT_SIZE_M = 0.8
MAX_ROBOT_SPEED = 0.08
DEFAULT_BATTERY_CAPACITY = 1000.0
RANDOM_TV_MAX_MPS = 2.0
RANDOM_RV_MAX_RADPS = 0.8
COLLISION_PUSH_FACTOR = 0.1

# --- ALGORITHM CONFIGURATION ---
RRT_STEP_SIZE = 20.0
RRT_MAX_ITERATIONS = 2000
RRT_GOAL_TOLERANCE = 15.0
APPROACH_DISTANCE_PX = 30.0
WAYPOINT_ARRIVAL_TOLERANCE_PX = 4.0
C_AMR_MARKOV_COLOR = QColor(255, 0, 0, 25)
DRAWING_RECT_COLOR = QColor(0, 150, 255, 150)
C_AMR_MISSION_PATH_COLOR = QColor(255, 0, 0, 200)
C_AMR_MISSION_PATH_WIDTH = 1.5
ROBOT_PATH_COLOR = QColor(0, 0, 255, 100)
ROBOT_PATH_WIDTH = 0.8

# --- COLORS ---
STATE_COLOR_IDLE = QColor("pink")
STATE_COLOR_MOVING = QColor("green")
STATE_COLOR_CHARGING = QColor("yellow")
STATE_COLOR_LOW_BATTERY = QColor("red")
SCENE_BG_COLOR = QColor(245, 245, 245)
GRID_PEN_COLOR = QColor(220, 220, 220)
BORDER_PEN_COLOR = QColor(0, 0, 0)
RRT_PATH_COLOR = QColor(255, 0, 255, 200)
MARKOV_BLANKET_COLOR = QColor(100, 100, 255, 128)
MARKOV_LINE_COLOR = QColor(0, 0, 255, 100)
OBSTACLE_WALKABLE_COLOR = QColor(230, 230, 230)
OBSTACLE_SOLID_PEN_COLOR = QColor("darkgray")
NODE_BRUSH_COLOR = QColor("lightgray")
STATION_BRUSH_COLOR = QColor("blue")
DRAWING_RECT_COLOR = QColor("red")
OBSTACLE_SOLID_COLOR = NODE_PEN_COLOR = QColor("gray")
STATION_PEN_COLOR = DIVIDER_PEN_COLOR = QColor("black")
C_AMR_COLOR = QColor("purple")
C_AMR_PATH_COLOR = QColor("cyan") 

# --- FONTS ---
ROBOT_ID_FONT = QFont("Arial", 8, QFont.Bold)
NODE_ID_FONT = QFont("Arial", 7)
INFO_FONT = QFont("Arial", 10)
